### ISSUE TITLE
Comment lines in control file break syntax highlighting of line(s) below

### ISSUE THREAD

**Issue by m-roberts** [barnumbirr/sublime-debian#6]
Without comment:
<img width="274" alt="Screenshot 2021-06-21 at 11 32 41" src="https://user-images.githubusercontent.com/2947595/122748710-6e1f6780-d284-11eb-8b69-a1ea176b8673.png">

With comment:
<img width="285" alt="Screenshot 2021-06-21 at 11 32 49" src="https://user-images.githubusercontent.com/2947595/122748704-6d86d100-d284-11eb-99c6-9659e35fd452.png">

**Comment by barnumbirr** [comment]
Nice catch! Can reproduce in v1.3.1.
`substvar` parsing seems to fall apart with comments and I'll need to investigate this a bit deeper.

**Comment by barnumbirr** [comment]
Issue present not only in `substvar` parsing:
![Capture2](https://user-images.githubusercontent.com/2029239/122963369-7eb80680-d386-11eb-9336-3afa69f9d654.PNG)

![Capture](https://user-images.githubusercontent.com/2029239/122963388-824b8d80-d386-11eb-9388-d972d07ee2e4.PNG)

**Comment by barnumbirr** [comment]
Should be fixed in [1.3.2](https://github.com/barnumbirr/sublime-debian/releases/tag/1.3.2), along with some other minor issues.
Thanks for reporting this! 🎉
